with open("src/App.jsx", "r") as f:
    lines = f.readlines()

new_lines = lines[:3042] + [
"\n// ==========================================\n",
"// UI2: CLINICAL CHART PAGE\n",
"// ==========================================\n",
"export function ClinicalChartPageUI2({ currentUI, setUI, isMobileMenuOpen, setIsMobileMenuOpen }) {\n",
"    const { selectedTeeth, toggleToothSelection, progressNotes } = useChartStore();\n",
"\n",
"    const derivedTeethState = React.useMemo(() => {\n",
"        const t = {};\n",
"        for (let i = 1; i <= 32; i++) t[i] = { status: \"Healthy\", condition: \"\", surfaces: [] };\n",
"        [...progressNotes].sort((a, b) => new Date(a.date) - new Date(b.date)).forEach(note => {\n",
"            if (!note.tooth) return;\n",
"            const toothNum = parseInt(note.tooth, 10);\n",
"            if (t[toothNum]) {\n",
"                if (note.code.startsWith('D7140') || note.code.includes('Extraction')) {\n",
"                    t[toothNum].status = 'Missing';\n",
"                } else if (note.status) {\n",
"                    t[toothNum].status = note.status;\n",
"                    if (note.surface && note.surface !== 'ALL') {\n",
"                        t[toothNum].surfaces = note.surface.split('');\n",
"                    } else {\n",
"                        t[toothNum].surfaces = [];\n",
"                    }\n",
"                }\n",
"            }\n",
"        });\n",
"        return t;\n",
"    }, [progressNotes]);\n",
"\n",
"    return (\n",
"        <div style={{ padding: \"0\", background: \"#f1f5f9\", height: \"calc(100vh - 72px)\", display: \"flex\", flexDirection: \"column\", overflow: \"hidden\" }}>\n",
"            <div style={{ background: \"white\", padding: \"16px 24px\", display: \"flex\", justifyContent: \"space-between\", alignItems: \"center\", borderBottom: \"1px solid #e2e8f0\", zIndex: 10 }}>\n",
"                <div style={{ display: \"flex\", alignItems: \"center\", gap: 16 }}>\n",
"                    <div style={{ width: 40, height: 40, background: \"#1e293b\", color: \"white\", borderRadius: 8, display: \"flex\", alignItems: \"center\", justifyContent: \"center\", fontWeight: \"bold\", fontSize: 18 }}>\n",
"                        {isMobileMenuOpen ? \"MM\" : \"SM\"}\n",
"                    </div>\n",
"                    <div>\n",
"                        <h2 style={{ fontSize: 20, fontWeight: 700, color: \"#0f172a\", margin: 0 }}>Sarah Martinez</h2>\n",
"                        <div style={{ fontSize: 13, color: \"#64748b\", marginTop: 2, display: \"flex\", gap: 12 }}>\n",
"                            <span>DOB: 04/12/1985 (39y)</span>\n",
"                            <span>Female</span>\n",
"                            <span>#10442</span>\n",
"                        </div>\n",
"                    </div>\n",
"                </div>\n",
"                <div style={{ display: \"flex\", gap: 12 }}>\n",
"                    <button style={{ padding: \"8px 16px\", borderRadius: 6, border: \"1px solid #e2e8f0\", background: \"white\", fontSize: 14, fontWeight: 600, color: \"#475569\", cursor: \"pointer\", display: \"flex\", alignItems: \"center\", gap: 8 }}>\n",
"                        <Printer size={16} /> Print Chart\n",
"                    </button>\n",
"                    <button style={{ padding: \"8px 16px\", borderRadius: 6, border: \"none\", background: \"#3b82f6\", color: \"white\", fontSize: 14, fontWeight: 600, cursor: \"pointer\", display: \"flex\", alignItems: \"center\", gap: 8 }}>\n",
"                        Save Clinical Notes\n",
"                    </button>\n",
"                </div>\n",
"            </div>\n",
"            <div style={{ display: \"flex\", flex: 1, overflow: \"hidden\" }}>\n",
"                 <div style={{ flex: \"1 1 60%\", background: \"#f8fafc\", position: \"relative\", borderRight: \"1px solid #e2e8f0\", display: \"flex\", flexDirection: \"column\" }}>\n",
"                    <div style={{ padding: \"16px 24px\", display: \"flex\", justifyContent: \"space-between\", alignItems: \"center\", background: \"white\", borderBottom: \"1px solid #e2e8f0\" }}>\n",
"                        <h3 style={{ fontSize: 16, fontWeight: 600, color: \"#0f172a\", margin: 0 }}>Odontogram</h3>\n",
"                        <div style={{ display: \"flex\", gap: 16 }}>\n",
"                            <div style={{ display: \"flex\", alignItems: \"center\", gap: 6 }}>\n",
"                                <div style={{ width: 12, height: 12, borderRadius: 2, background: \"#3b82f6\" }}></div>\n",
"                                <span style={{ fontSize: 12, color: \"#64748b\" }}>Completed</span>\n",
"                            </div>\n",
"                            <div style={{ display: \"flex\", alignItems: \"center\", gap: 6 }}>\n",
"                                <div style={{ width: 12, height: 12, borderRadius: 2, background: \"#ef4444\" }}></div>\n",
"                                <span style={{ fontSize: 12, color: \"#64748b\" }}>Treatment Plan</span>\n",
"                            </div>\n",
"                            <div style={{ display: \"flex\", alignItems: \"center\", gap: 6 }}>\n",
"                                <div style={{ width: 12, height: 12, borderRadius: 2, background: \"#10b981\" }}></div>\n",
"                                <span style={{ fontSize: 12, color: \"#64748b\" }}>Existing</span>\n",
"                            </div>\n",
"                            <div style={{ display: \"flex\", alignItems: \"center\", gap: 6 }}>\n",
"                                <div style={{ width: 12, height: 12, borderRadius: 2, background: \"#f59e0b\" }}></div>\n",
"                                <span style={{ fontSize: 12, color: \"#64748b\" }}>Watch</span>\n",
"                            </div>\n",
"                            <div style={{ display: \"flex\", alignItems: \"center\", gap: 6 }}>\n",
"                                <div style={{ width: 12, height: 12, borderRadius: 2, background: \"#111827\" }}></div>\n",
"                                <span style={{ fontSize: 12, color: \"#64748b\" }}>Condition</span>\n",
"                            </div>\n",
"                        </div>\n",
"                    </div>\n",
"                    <div style={{ flex: 1, position: \"relative\" }}>\n",
"                        {selectedTeeth.length > 0 && (\n",
"                            <div style={{ position: \"absolute\", top: 16, left: 16, zIndex: 10, background: \"white\", padding: \"8px 16px\", borderRadius: 8, boxShadow: \"0 4px 6px -1px rgb(0 0 0 / 0.1)\", border: \"1px solid #e2e8f0\" }}>\n",
"                                <span style={{ fontSize: 13, color: \"#64748b\", fontWeight: 500 }}>Selected Tooth: </span>\n",
"                                <span style={{ fontSize: 16, color: \"#0f172a\", fontWeight: 700 }}>#{selectedTeeth.join(', ')}</span>\n",
"                            </div>\n",
"                        )}\n",
"                        <Dental3DModel \n",
"                            teethState={derivedTeethState} \n",
"                            selectedTooth={selectedTeeth.length > 0 ? selectedTeeth[selectedTeeth.length - 1] : null} \n",
"                            onSelectTooth={(toothId) => toggleToothSelection(toothId)} \n",
"                        />\n",
"                    </div>\n",
"                </div>\n",
"                <div style={{ width: \"40%\", background: \"white\", display: \"flex\", flexDirection: \"column\", minWidth: 400 }}>\n",
"                    <div style={{ height: \"55%\", display: \"flex\", flexDirection: \"column\", borderBottom: \"1px solid #e2e8f0\" }}>\n",
"                        <ProcedureEntryPanel />\n",
"                    </div>\n",
"                    <div style={{ height: \"45%\", display: \"flex\", flexDirection: \"column\", background: \"#f8fafc\" }}>\n",
"                        <ProgressNotes />\n",
"                    </div>\n",
"                </div>\n",
"            </div>\n",
"        </div>\n",
"    );\n",
"}\n"
] + lines[3156:]

with open("src/App.jsx", "w") as f:
    f.writelines(new_lines)
